name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
         # Username used to log against the Docker registry
         username: ${{ secrets.REGISTRY_USERNAME }}
         # Password or personal access token used to log against the Docker registry
         password: ${{ secrets.REGISTRY_PASSWORD }}
          
    - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2.2.1
        env:
          SLACK_ICON_EMOJI: ':bell:'
          SLACK_CHANNEL: project
          SLACK_MESSAGE: 'Build/Push Images :building_construction: - ${{job.status}}'
          SLACK_USERNAME: Github
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          
